Sun Oct  8 22:04:04 UTC 2023
WARNING 2023-10-08T22:04:06.830+00:00 lsst.resources._resourcePath ()(_resourcePath.py:166) - Possible double encoding of /home/ameisner/test/fresh_pipeline_no_char/nb9b_det_deblend_meas.yaml#detection%2Cdeblend_single%2Cmeasure
WARNING 2023-10-08T22:04:12.892+00:00 py.warnings ()(warnings.py:109) - /opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/pipe_tasks/g369a80f31c+b9be13ffc2/python/lsst/pipe/tasks/multiBand.py:261: UserWarning: MeasureMergedCoaddSourcesConnections.defaultTemplates is deprecated and no longer used. Use MeasureMergedCoaddSourcesConfig.inputCatalog.
  warnings.warn("MeasureMergedCoaddSourcesConnections.defaultTemplates is deprecated and no longer used. "

WARNING 2023-10-08T22:04:13.081+00:00 py.warnings ()(warnings.py:109) - /opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/pex_config/g71c1dbb2b5+9a7299d786/python/lsst/pex/config/configurableField.py:79: FutureWarning: Call to deprecated class LoadIndexedReferenceObjectsConfig. (This config is no longer used; it will be removed after v25. Please use LoadReferenceObjectsConfig instead.) -- Deprecated since version v25.0.
  value = self._ConfigClass(__name=name, __at=at, __label=label, **storage)

WARNING 2023-10-08T22:04:13.082+00:00 py.warnings ()(warnings.py:109) - /opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/pex_config/g71c1dbb2b5+9a7299d786/python/lsst/pex/config/configurableField.py:359: FutureWarning: Call to deprecated class LoadIndexedReferenceObjectsConfig. (This config is no longer used; it will be removed after v25. Please use LoadReferenceObjectsConfig instead.) -- Deprecated since version v25.0.
  value = oldValue.ConfigClass()

ERROR 2023-10-08T22:04:13.253+00:00 lsst.daf.butler.cli.utils ()(utils.py:1093) - Caught an exception, details are in traceback:
Traceback (most recent call last):
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/pipe_base/gbbd6c36fd7+a713711289/python/lsst/pipe/base/pipeline.py", line 881, in makeDatasetTypesSet
    datasetType = registry.getDatasetType(c.name)
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/daf_butler/g35a551b10e+17c7ad0751/python/lsst/daf/butler/registries/sql.py", line 422, in getDatasetType
    return self._managers.datasets[name].datasetType
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/daf_butler/g35a551b10e+17c7ad0751/python/lsst/daf/butler/registry/interfaces/_datasets.py", line 599, in __getitem__
    raise KeyError(f"Dataset type with name '{name}' not found.")
KeyError: "Dataset type with name 'cal_ref_cat' not found."

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/ctrl_mpexec/g993939a6a1+f01622d10f/python/lsst/ctrl/mpexec/cli/cmd/commands.py", line 159, in run
    qgraph = script.qgraph(pipelineObj=pipeline, **kwargs, show=show)
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/ctrl_mpexec/g993939a6a1+f01622d10f/python/lsst/ctrl/mpexec/cli/script/qgraph.py", line 196, in qgraph
    qgraph = f.makeGraph(pipelineObj, args)
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/ctrl_mpexec/g993939a6a1+f01622d10f/python/lsst/ctrl/mpexec/cmdLineFwk.py", line 563, in makeGraph
    qgraph = graphBuilder.makeGraph(
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/pipe_base/gbbd6c36fd7+a713711289/python/lsst/pipe/base/graphBuilder.py", line 1275, in makeGraph
    scaffolding = _PipelineScaffolding(pipeline, registry=self.registry)
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/pipe_base/gbbd6c36fd7+a713711289/python/lsst/pipe/base/graphBuilder.py", line 567, in __init__
    datasetTypes = PipelineDatasetTypes.fromPipeline(pipeline, registry=registry)
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/pipe_base/gbbd6c36fd7+a713711289/python/lsst/pipe/base/pipeline.py", line 1152, in fromPipeline
    thisTask = TaskDatasetTypes.fromTaskDef(
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/pipe_base/gbbd6c36fd7+a713711289/python/lsst/pipe/base/pipeline.py", line 1015, in fromTaskDef
    prerequisites=makeDatasetTypesSet("prerequisiteInputs", is_input=True),
  File "/opt/lsst/software/stack/stack/miniconda3-py38_4.9.2-4.1.0/Linux64/pipe_base/gbbd6c36fd7+a713711289/python/lsst/pipe/base/pipeline.py", line 883, in makeDatasetTypesSet
    raise LookupError(
LookupError: DatasetType 'cal_ref_cat' referenced by MeasureMergedCoaddSourcesConnections uses 'skypix' as a dimension placeholder, but does not already exist in the registry.  Note that reference catalog names are now used as the dataset type name instead of 'ref_cat'.
Sun Oct  8 22:04:13 UTC 2023
